### ISSUE TITLE
Docs : Add time and space complexities of various algorithms

### ISSUE THREAD

**Issue by sibasish14** [sr6033/dataStructure-Algorithms#8]
We should add a document containing details about the space and time complexities of various algorithms.
This will provide a way to compare different algorithms.

**Comment by sr6033** [comment]
Try to add this.

**Comment by sibasish14** [comment]
@sr6033  Should I write a .doc file or a .rst file?
** I don't know how to create tables with .rst files though.

**Comment by sr6033** [comment]
We can create a wiki page here.
